name = input("Enter your name: ")
age = input("Enter your age: ")
Birthyear = input("Enter your birth year: ")
Birthmonth = input("Enter your birth month: ")
Birthdate = input("Enter your birth date: ")
print(f"{name} is {age} and was born on {Birthmonth} {Birthdate}th, {Birthyear}.")
